---
title: Al3x.Net
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
enforce_ssl: al3x.net
highlighter: rouge
livereload: true
lsi: false
markdown: kramdown
port: 3000
url: https://al3x.net
